export const municipios =
  [
    { municipio: 'agua-branca' },
    { municipio: 'anadia' },
    { municipio: 'arapiraca' },
    { municipio: 'atalaia' },
    { municipio: 'barra-de-santo-antonio' },
    { municipio: 'barra-de-sao-miguel' },
    { municipio: 'batalha' },
    { municipio: 'belem' },
    { municipio: 'belo-monte' },
    { municipio: 'branquinha' },
    { municipio: 'cacimbinhas' },
    { municipio: 'cajueiro' },
    { municipio: 'campestre' },
    { municipio: 'campo-alegre' },
    { municipio: 'campo-grande' },
    { municipio: 'canapi' },
    { municipio: 'capela' },
    { municipio: 'carneiros' },
    { municipio: 'cha-preta' },
    { municipio: 'coite-do-noia' },
    { municipio: 'colonia-leopoldina' },
    { municipio: 'coqueiro-seco' },
    { municipio: 'coruripe' },
    { municipio: 'craibas' },
    { municipio: 'delmiro-gouveia' },
    { municipio: 'dois-riachos' },
    { municipio: 'estrela-de-alagoas' },
    { municipio: 'feira-grande' },
    { municipio: 'feliz-deserto' },
    { municipio: 'flexeiras' },
    { municipio: 'girau-do-ponciano' },
    { municipio: 'geral' },
    { municipio: 'ibateguara' },
    { municipio: 'igaci' },
    { municipio: 'igreja-nova' },
    { municipio: 'inhapi' },
    { municipio: 'jacare-dos-homens' },
    { municipio: 'jacuipe' },
    { municipio: 'japaratinga' },
    { municipio: 'jaramataia' },
    { municipio: 'jequia-da-praia' },
    { municipio: 'joaquim-gomes' },
    { municipio: 'jundia' },
    { municipio: 'junqueiro' },
    { municipio: 'lagoa-da-canoa' },
    { municipio: 'limoeiro-de-anadia' },
    { municipio: 'major-izidoro' },
    { municipio: 'mar-vermelho' },
    { municipio: 'maragogi' },
    { municipio: 'maravilha' },
    { municipio: 'marechal-deodoro' },
    { municipio: 'maribondo' },
    { municipio: 'mata-grande' },
    { municipio: 'messias' },
    { municipio: 'minador-do-negrao' },
    { municipio: 'monteiropolis' },
    { municipio: 'murici' },
    { municipio: 'novo-lino' },
    {
      municipio:
        "olho-d agua-do-casado"
    },
    {
      municipio:
        "olho-d agua-grande"
    },
    {
      municipio:
        "olho-d'agua-das-flores"
    },
    { municipio: 'olivenca' },
    { municipio: 'ouro-branco' },
    { municipio: 'palestina' },
    { municipio: 'pao-de-acucar' },
    { municipio: 'pariconha' },
    { municipio: 'paulo-jacinto' },
    { municipio: 'piacabucu' },
    { municipio: 'pilar' },
    { municipio: 'pindoba' },
    { municipio: 'piranhas' },
    { municipio: 'poco-das-trincheiras' },
    { municipio: 'porto-calvo' },
    { municipio: 'porto-de-pedras' },
    { municipio: 'porto-real-do-colegio' },
    { municipio: 'quebrangulo' },
    { municipio: 'rio-largo' },
    { municipio: 'roteiro' },
    { municipio: 'santa-luzia-do-norte' },
    { municipio: 'santana-do-ipanema' },
    { municipio: 'santana-do-mundau' },
    { municipio: 'sao-jose-da-laje' },
    { municipio: 'sao-jose-da-tapera' },
    { municipio: 'sao-luis-do-quitunde' },
    {
      municipio:
        "sao-miguel-dos-milagres"
    },
    { municipio: 'sao-sebastiao' },
    { municipio: 'satuba' },
    { municipio: 'senador-rui-palmeira' },
    {
      municipio:
        "tanque-d arca"
    },
    { municipio: 'taquarana' },
    { municipio: 'teotonio-vilela' },
    { municipio: 'traipu' },
    { municipio: 'vicosa' }

  ]